title: "Ancient Greek PROIEL and PERSEUS MODELS"
description: "This project trains seven spaCy models using the ancient Greek Universal Dependency treebanks Proiel and Perseus."
email: "jmyerston@ucsd.edu"
source: "https://universaldependencies.org/"
vars:
  license: "MIT"
  author: "Jacobo Myerston"
  config_sm: "small"
  config_md: "medium"
  config_lg: "large"
  config_trf_proiel: "transformer_proiel"
  config_trf_perseus: "transformer_perseus"
  config_nsm: "ner_sm"
  config_nlg: "ner_lg"
  config_ntrf: "transformer_ner"
  config_lsm: "lemmatizer_sm"
  config_llg: "lemmatizer_vec"
  config_ltrf: "lemmatizer_trf"
  lang: "grc"
  treebank_proiel: "UD_Ancient_Greek-PROIEL"
  treebank_perseus: "UD_Ancient_Greek-Perseus"
  vectors_lg: "grc_floret_cbow_nn2_xn10_b200k_dim300.floret"
  train_name_proiel: "grc_proiel-ud-train"
  dev_name_proiel: "grc_proiel-ud-dev"
  test_name_proiel: "grc_proiel-ud-test"
  train_name_perseus: "grc_perseus-ud-train"
  dev_name_perseus: "grc_perseus-ud-dev"
  test_name_perseus: "grc_perseus-ud-test"
  pack_name_proiel: "proiel"
  pack_name_perseus: "perseus"
  pack_name_grecy: "lemma"
  pack_name_ner: "ner"

  package_version: 3.7.5
  gpu: 0

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "corpus","training", "configs", "packages", "vectors"]

assets:
  # - dest: "assets/${vars.treebank_proiel}"
  #   git:
  #     repo: "https://github.com/jmyerston/${vars.treebank_proiel}"
  #     branch: "master"
  #     path: ""

  # - dest: "assets/${vars.treebank_perseus}"
  #   git:
  #     repo: "https://github.com/jmyerston/${vars.treebank_perseus}"
  #     branch: "master"
  #     path: ""
      
  - dest: 'assets/${vars.vectors_lg}'
    url: 'https://zenodo.org/record/5733373/files/grc_floret_cbow_nn2_xn10_b200k_dim300.floret'


workflows:
  all:
    - preprocess
    - train-small-lemmatizer
    - train-large-lemmatizer
    - train-transformer-lemmatizer
    - train-transformer-ner
    - train-small-proiel
    - train-small-perseus
    - train-large-proiel
    - train-large-perseus
    - train-transformer-proiel
    - train-transformer-perseus
    - pack-small-proiel
    - pack-small-perseus
    - pack-large-proiel
    - pack-large-perseus
    - pack-transformer-proiel
    - pack-transformer-perseus
    - pack-transformer-ner
    - pack-transformer-lemmatizer

commands:

  - name: preprocess
    help: "Convert the data to spaCy's format"
    script:
      - "mkdir -p vectors/large"
      # - "python -m spacy convert assets/${vars.treebank_proiel}/${vars.train_name_proiel}.conllu corpus/parser/proiel/train --converter conllu --n-sents 10 --merge-subtokens"
      # - "python -m spacy convert assets/${vars.treebank_proiel}/${vars.dev_name_proiel}.conllu corpus/parser/proiel/dev --converter conllu --n-sents 10 --merge-subtokens"
      # - "python -m spacy convert assets/${vars.treebank_perseus}/${vars.train_name_perseus}.conllu corpus/parser/perseus/train --converter conllu --n-sents 10 --merge-subtokens"
      # - "python -m spacy convert assets/${vars.treebank_perseus}/${vars.dev_name_perseus}.conllu corpus/parser/perseus/dev --converter conllu --n-sents 10 --merge-subtokens"
      - "python -m spacy init vectors ${vars.lang} assets/${vars.vectors_lg} ./vectors/large --mode floret"

    deps:
      - "assets/${vars.treebank_proiel}/${vars.train_name_proiel}.conllu"
      - "assets/${vars.treebank_proiel}/${vars.dev_name_proiel}.conllu"
      - "assets/${vars.treebank_proiel}/${vars.test_name_proiel}.conllu"
      - "assets/${vars.treebank_perseus}/${vars.train_name_perseus}.conllu"
      - "assets/${vars.treebank_perseus}/${vars.dev_name_perseus}.conllu"

    outputs:
      - "corpus/parser/proiel/train/grc_proiel-ud-train.spacy"
      - "corpus/parser/proiel/dev/grc_proiel-ud-dev.spacy"
      - "corpus/parser/perseus/train/grc_perseus-ud-train.spacy"
      - "corpus/parser/perseus/dev/grc_perseus-ud-dev.spacy"
      - "vectors/${vars.vectors_lg}"

  - name: train-small-lemmatizer
    help: "Train the lemmatizer for the small model"
    script:
      - "mkdir -p training/lemmatizer/small"
      - "python -m spacy train configs/${vars.config_lsm}.cfg --output training/lemmatizer/small --gpu-id ${vars.gpu} --paths.train corpus/lemmatizer/train --paths.dev corpus/lemmatizer/dev --nlp.lang=${vars.lang}"
    deps:
      - "corpus/lemmatizer/train/lemma_train.spacy"
      - "corpus/lemmatizer/train/lemma_train.spacy"
      - "configs/${vars.config_lsm}.cfg"
    outputs:
      - "training/lemmatizer/small"

  - name: train-large-lemmatizer
    help: "Train the lemmatizer for the large model"
    script:
      - "mkdir -p training/lemmatizer/large"
      - "python -m spacy train configs/${vars.config_llg}.cfg --output training/lemmatizer/large --gpu-id ${vars.gpu} --paths.train corpus/lemmatizer/train  --paths.dev corpus/lemmatizer/dev --paths.vectors vectors/large --nlp.lang=${vars.lang}"
    deps:
      - "corpus/lemmatizer/train/lemma_train.spacy"
      - "corpus/lemmatizer/train/lemma_train.spacy"
      - "configs/${vars.config_llg}.cfg"
    outputs:
      - "training/lemmatizer/large"

  - name: train-transformer-lemmatizer
    help: "Train the lemmatizer for the transformer model"
    script:
      - "mkdir -p training/lemmatizer/transformer"
      - "python -m spacy train configs/${vars.config_ltrf}.cfg  --output ./training/lemmatizer/transformer --gpu-id ${vars.gpu} --paths.train corpus/lemmatizer/train --paths.dev corpus/lemmatizer/dev --nlp.lang=${vars.lang}"
    deps:
      - "configs/${vars.config_ltrf}.cfg"
    outputs:
      - "training/lemmatizer/transformer" 

### Training NER pipelines

  - name: train-transformer-ner
    help: "Train ${vars.treebank_proiel}"
    script:
      - "mkdir -p training/transformer/ner"
      - "python -m spacy train configs/${vars.config_ntrf}.cfg --output training/transformer/ner --gpu-id ${vars.gpu} --paths.train corpus/parser/proiel/train/ner_train.spacy --paths.dev corpus/parser/proiel/dev/ner_dev.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/proiel/train/ner_train.spacy"
      - "corpus/parser/proiel/dev/ner_dev.spacy"
      - "configs/${vars.config_ntrf}.cfg"
    outputs:
      - "training/ner/transformer"

## Training Parsers

  - name: train-small-proiel
    help: "Train ${vars.treebank_proiel}"
    script:
      - "mkdir -p training/small/proiel/assembled"
      - "python -m spacy train configs/${vars.config_sm}.cfg --output training/small/proiel/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/proiel/train --paths.dev corpus/parser/proiel/dev --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/proiel/train/grc_proiel-ud-train.spacy"
      - "corpus/parser/proiel/train/ner_train.spacy"
      - "corpus/parser/proiel/dev/grc_proiel-ud-dev.spacy"
      - "corpus/parser/proiel/dev/ner_dev.spacy"
      - "configs/${vars.config_sm}.cfg"
    outputs:
      - "training/small/proiel/assembled"

  - name: train-small-perseus
    help: "Train ${vars.treebank_perseus}"
    script:
      - "mkdir -p training/small/perseus/assembled"
      - "python -m spacy train configs/${vars.config_sm}.cfg --output training/small/perseus/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/perseus/train --paths.dev corpus/parser/perseus/dev --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/perseus/train/grc_perseus-ud-train.spacy"
      - "corpus/parser/perseus/train/ner_train.spacy"
      - "corpus/parser/perseus/dev/grc_perseus-ud-dev.spacy"
      - "corpus/parser/perseus/dev/ner_dev.spacy"
      - "configs/${vars.config_sm}.cfg"
    outputs:
      - "training/small/perseus/assembled"

  - name: train-large-proiel
    help: "Train ${vars.treebank_proiel}"
    script:
      - "mkdir -p training/large/assembled"
      - "python -m spacy train configs/${vars.config_lg}.cfg --output training/large/proiel/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/proiel/train --paths.dev corpus/parser/proiel/dev --paths.vectors vectors/large --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/proiel/train/grc_proiel-ud-train.spacy"
      - "corpus/parser/proiel/train/ner_train.spacy"
      - "corpus/parser/proiel/dev/grc_proiel-ud-dev.spacy"
      - "corpus/parser/proiel/dev/ner_dev.spacy"
      - "configs/${vars.config_lg}.cfg"
    outputs:
      - "training/large/proiel/assembled"

  - name: train-large-perseus
    help: "Train ${vars.treebank_perseus}"
    script:
      - "mkdir -p training/large/perseus/assembled"
      - "python -m spacy train configs/${vars.config_lg}.cfg --output training/large/perseus/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/perseus/train --paths.dev corpus/parser/perseus/dev --paths.vectors vectors/large --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/perseus/train/grc_perseus-ud-train.spacy"
      - "corpus/parser/perseus/train/ner_train.spacy"
      - "corpus/parser/perseus/dev/grc_perseus-ud-dev.spacy"
      - "corpus/parser/perseus/dev/ner_dev.spacy"
      - "configs/${vars.config_lg}.cfg"
    outputs:
      - "training/large/perseus/assembled"

  - name: train-transformer-proiel
    help: "Train ${vars.treebank_proiel}"
    script:
      - "mkdir -p training/transformer/proiel/assembled"
      - "python -m spacy train configs/${vars.config_trf_proiel}.cfg --output training/transformer/proiel/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/proiel/train/grc_proiel-ud-train.spacy --paths.dev corpus/parser/proiel/dev/grc_proiel-ud-dev.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/proiel/train/grc_proiel-ud-train.spacy"
      - "corpus/parser/proiel/dev/grc_proiel-ud-dev.spacy"
      - "configs/${vars.config_trf_proiel}.cfg"
    outputs:
      - "training/transformer/proiel/assembled"

  - name: train-transformer-perseus
    help: "Train ${vars.treebank_perseus}"
    script:
      - "mkdir -p training/transformer/perseus/assembled"
      - "python -m spacy train configs/${vars.config_trf_perseus}.cfg --output training/transformer/perseus/assembled --gpu-id ${vars.gpu} --paths.train corpus/parser/perseus/train/grc_perseus-ud-train.spacy --paths.dev corpus/parser/perseus/dev/grc_perseus-ud-dev.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/parser/perseus/train/grc_perseus-ud-train.spacy"
      - "corpus/parser/perseus/dev/grc_perseus-ud-dev.spacy"
      - "configs/${vars.config_trf_perseus}.cfg"
    outputs:
      - "training/transformer/perseus/assembled"

## Packing 

  - name: pack-small-proiel
    help: "pack the trained model"
    script:
      - "python -m spacy package training/small/proiel/assembled/model-best packages --name ${vars.pack_name_proiel}_sm --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/small/proiel/assembled"
    outputs_no_cache:
      - "package/${vars.lang}_${vars.pack_name_proiel}_sm-${vars.package_version}/dist/grc_${vars.pack_name_proiel}config_sm-${vars.package_version}.tar.gz"

  - name: pack-small-perseus
    help: "pack the trained model"
    script:
      - "python -m spacy package training/small/perseus/assembled/model-best packages --name ${vars.pack_name_perseus}_sm --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/small/perseus/assembled"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_perseus}_sm-${vars.package_version}/dist/grc_${vars.pack_name_perseus}config_sm-${vars.package_version}.tar.gz"
 
  - name: pack-large-proiel
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package training/large/proiel/assembled/model-best packages --name ${vars.pack_name_proiel}_lg --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/large/proiel/assembled/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_proiel}_lg-${vars.package_version}/dist/grc_${vars.pack_name_proiel}config_lg-${vars.package_version}.tar.gz"

  - name: pack-large-perseus
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package training/large/perseus/assembled/model-best packages --name ${vars.pack_name_perseus}_lg --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/large/perseus/assembled/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_perseus}_lg-${vars.package_version}/dist/grc_${vars.pack_name_perseus}config_lg-${vars.package_version}.tar.gz"

  - name: pack-transformer-proiel
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package training/transformer/proiel/assembled/model-best packages --name ${vars.pack_name_proiel}_trf --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/transformer/proiel/assembled/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_proiel}_trf-${vars.package_version}/dist/grc_${vars.pack_name_proiel}config_trf-${vars.package_version}.tar.gz"

  - name: pack-transformer-ner
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package training/transformer/ner/model-best packages --name ${vars.pack_name_ner}_trf --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/transformer/ner/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_ner}_trf-${vars.package_version}/dist/grc_${vars.pack_name_ner}config_trf-${vars.package_version}.tar.gz"
  
  - name: pack-transformer-perseus
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package training/transformer/perseus/assembled/model-best packages --name ${vars.pack_name_perseus}_trf --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/transformer/perseus/assembled/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.pack_name_perseus}_trf-${vars.package_version}/dist/grc_${vars.pack_name_perseus}config_trf-${vars.package_version}.tar.gz"
    
  - name: pack-transformer-lemmatizer
    help: "pack the trained model so it can be installed"
    script:
      - "python -m spacy package ./training/lemmatizer/greCy_lemmatizer/model-best packages --name ${vars.pack_name_grecy}_trf --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/lemmatizer/greCy_lemmatizer/model-best"
    outputs_no_cache:
      - "packages/${vars.pack_name_grecy}_trf-${vars.package_version}/dist/grc_${vars.pack_name_grecy}config_trf-${vars.package_version}.tar.gz"

## Pushing the packages to Huggingface

  - name: push-small-proiel
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_proiel}_sm-${vars.package_version}/dist/grc_${vars.pack_name_proiel}_sm-${vars.package_version}-py3-none-any.whl"
       
  - name: push-large-proiel
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_proiel}_lg-${vars.package_version}/dist/grc_${vars.pack_name_proiel}_lg-${vars.package_version}-py3-none-any.whl"

  - name: push-transformer-proiel
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_proiel}_trf-${vars.package_version}/dist/grc_${vars.pack_name_proiel}_trf-${vars.package_version}-py3-none-any.whl" 

  - name: push-small-perseus
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_perseus}_sm-${vars.package_version}/dist/grc_${vars.pack_name_perseus}_sm-${vars.package_version}-py3-none-any.whl"
       
  - name: push-large-perseus
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_perseus}_lg-${vars.package_version}/dist/grc_${vars.pack_name_perseus}_lg-${vars.package_version}-py3-none-any.whl"

  - name: push-transformer-perseus
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_perseus}_trf-${vars.package_version}/dist/grc_${vars.pack_name_perseus}_trf-${vars.package_version}-py3-none-any.whl"

  - name: push-transformer-lemmatizer
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_grecy}_trf-${vars.package_version}/dist/grc_${vars.pack_name_grecy}_trf-${vars.package_version}-py3-none-any.whl" 

  - name: push-transformer-ner
    help: "Pushes the packd model to the huggingface hub"
    script:
    - "python -m spacy huggingface-hub push packages/${vars.lang}_${vars.pack_name_ner}_trf-${vars.package_version}/dist/grc_${vars.pack_name_ner}_trf-${vars.package_version}-py3-none-any.whl" 

## Cleaning Up

  - name: clean-spring
    help: "Clean directories"
    script:
      - "rm -rf packages"
      - "rm -rf training"

  - name: clean-all
    help: "Clean directories"
    script:
      - "rm -rf packages"
      - "rm -rf training"
      - "rm -rf vectors"