title: "UD_Ancient_Greek-PROIEL"
description: "This project to train a part-of-speech tagger, morphologizer, and dependency parser from the ancient Greek Universal Dependency treebank Proiel."

spacy_version: ">=3.4,<4.0.0"
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  config_sm: "small"
  config_md: "medium"
  config_lg: "large"
  config_trf: "transformer"
  lang: "grc"
  treebank: "UD_Ancient_Greek-PROIEL"
  vectors_md: "grc_floret_cbow_nn2_xn10_b50k_dim300.floret"
  vectors_lg: "grc_floret_cbow_nn2_xn10_b200k_dim300.floret"
  train_name: "grc_proiel-ud-train"
  dev_name: "grc_proiel-ud-dev"
  test_name: "grc_proiel-ud-test"
  package_name: "ud_proiel"
  package_version: "3.4.0"
  gpu: 0

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets", "corpus","training","configs", "packages", "vectors"]

assets:
  - dest: "assets/${vars.treebank}"
    git:
      repo: "https://github.com/UniversalDependencies/${vars.treebank}"
      branch: "master"
      path: ""

  - dest: 'assets/${vars.vectors_md}'
    url: 'https://zenodo.org/record/5733373/files/grc_floret_cbow_nn2_xn10_b50k_dim300.floret'

  - dest: 'assets/${vars.vectors_lg}'
    url: 'https://zenodo.org/record/5733373/files/grc_floret_cbow_nn2_xn10_b200k_dim300.floret'


workflows:
  all:
    - preprocess
    - train-small
    - train-medium
    - train-large
    - train-transformer
    - evaluate-small
    - evaluate-medium
    - evaluate-large
    - evaluate-transformer
    - package-small
    - package-medium
    - package-large
    - package-transformer

commands:

  - name: preprocess
    help: "Convert the data to spaCy's format"
    script:
      - "mkdir -p corpus/${vars.treebank}"
      - "mkdir -p vectors/medium"
      - "mkdir -p vectors/large"
      - "mkdir -p metrics/small"
      - "mkdir -p metrics/medium"
      - "mkdir -p metrics/large"
      - "mkdir -p metrics/transformer"
      - "python -m spacy convert assets/${vars.treebank}/${vars.train_name}.conllu corpus/${vars.treebank}/ --converter conllu --n-sents 10 --merge-subtokens"
      - "python -m spacy convert assets/${vars.treebank}/${vars.dev_name}.conllu corpus/${vars.treebank}/ --converter conllu --n-sents 10 --merge-subtokens"
      - "python -m spacy convert assets/${vars.treebank}/${vars.test_name}.conllu corpus/${vars.treebank}/ --converter conllu --n-sents 10 --merge-subtokens"
      - "mv corpus/${vars.treebank}/${vars.train_name}.spacy corpus/${vars.treebank}/train.spacy"
      - "mv corpus/${vars.treebank}/${vars.dev_name}.spacy corpus/${vars.treebank}/dev.spacy"
      - "mv corpus/${vars.treebank}/${vars.test_name}.spacy corpus/${vars.treebank}/test.spacy"
      - "python -m spacy init vectors ${vars.lang} assets/${vars.vectors_md} ./vectors/medium --mode floret"
      - "python -m spacy init vectors ${vars.lang} assets/${vars.vectors_lg} ./vectors/large --mode floret"
#      - "python -m spacy init labels ./configs/${vars.config_trf}.cfg ./data/labels --paths.train ./corpus/${vars.treebank}/train.spacy  --paths.dev ./corpus/${vars.treebank}/dev.spacy --verbose --gpu-id 0"

    deps:
      - "assets/${vars.treebank}/${vars.train_name}.conllu"
      - "assets/${vars.treebank}/${vars.dev_name}.conllu"
      - "assets/${vars.treebank}/${vars.test_name}.conllu"

    outputs:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "vectors/${vars.vectors_md}"
      - "vectors/${vars.vectors_lg}"

  - name: train-small
    help: "Train ${vars.treebank}"
    script:
      - "mkdir -p training/small"
      - "python -m spacy train configs/${vars.config_sm}.cfg --output training/small --gpu-id ${vars.gpu} --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "configs/${vars.config_sm}.cfg"
    outputs:
      - "training/small"

  - name: package-small
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/small/model-best packages --name ${vars.package_name}_sm --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/small/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.package_name}_sm-${vars.package_version}/dist/grc_${vars.package_name}config_sm-${vars.package_version}.tar.gz"

  - name: train-medium
    help: "Train ${vars.treebank}"
    script:
      - "mkdir -p training/medium"
      - "python -m spacy train configs/${vars.config_md}.cfg --output training/medium --gpu-id ${vars.gpu} --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy  --paths.vectors/vectors/medium --nlp.lang=${vars.lang}"
    deps:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "configs/${vars.config_md}.cfg"
    outputs:
      - "training/medium"

  - name: package-medium
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/medium/model-best packages --name ${vars.package_name}_md --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/medium/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.package_name}_md-${vars.package_version}/dist/grc_${vars.package_name}config_md-${vars.package_version}.tar.gz"

  - name: train-large
    help: "Train ${vars.treebank}"
    script:
      - "mkdir -p training/large"
      - "python -m spacy train configs/${vars.config_lg}.cfg --output training/large --gpu-id ${vars.gpu} --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --paths.vectors/vectors/large --nlp.lang=${vars.lang}"
    deps:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "configs/${vars.config_lg}.cfg"
    outputs:
      - "training/large"

  - name: package-large
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/large/model-best packages --name ${vars.package_name}_lg --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/large/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.package_name}_lg-${vars.package_version}/dist/grc_${vars.package_name}config_lg-${vars.package_version}.tar.gz"

  - name: train-transformer
    help: "Train ${vars.treebank}"
    script:
      - "mkdir -p training/transformer"
      - "python -m spacy train configs/${vars.config_trf}.cfg --output training/transformer --gpu-id ${vars.gpu} --paths.train corpus/${vars.treebank}/train.spacy --paths.dev corpus/${vars.treebank}/dev.spacy --nlp.lang=${vars.lang}"
    deps:
      - "corpus/${vars.treebank}/train.spacy"
      - "corpus/${vars.treebank}/dev.spacy"
      - "configs/${vars.config_trf}.cfg"
    outputs:
      - "training/transformer"

  - name: package-transformer
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/transformer/model-best packages --name ${vars.package_name}_trf --version ${vars.package_version} --build wheel --force"
    deps:
      - "training/transformer/model-best"
    outputs_no_cache:
      - "packages/${vars.lang}_${vars.package_name}_trf-${vars.package_version}/dist/grc_${vars.package_name}config_trf-${vars.package_version}.tar.gz"
  
  - name: evaluate-small
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate ./training/small/model-best ./corpus/${vars.treebank}/test.spacy --output ./training/small/model-best/accuracy.json --gpu-id ${vars.gpu}"
    deps:
      - "training/small/model-best"
      - "corpus/${vars.treebank}/test.spacy"

  - name: evaluate-medium
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate ./training/medium/model-best ./corpus/${vars.treebank}/test.spacy --output ./training/medium/model-best/accuracy.json --gpu-id ${vars.gpu}"
    deps:
      - "training/medium/model-best"
      - "corpus/${vars.treebank}/test.spacy"

  - name: evaluate-large
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate ./training/large/model-best ./corpus/${vars.treebank}/test.spacy --output ./training/large/model-best/accuracy.json --gpu-id ${vars.gpu}"
    deps:
      - "training/large/model-best"
      - "corpus/${vars.treebank}/test.spacy"
    outputs:
      - "training/large/accuracy.json"

  - name: evaluate-transformer
    help: "Evaluate on the test data and save the metrics"
    script:
      - "python -m spacy evaluate ./training/transformer/model-best ./corpus/${vars.treebank}/test.spacy --output ./training/transformer/model-best/accuracy.json --gpu-id ${vars.gpu}"
    deps:
      - "training/transformer/model-best"
      - "corpus/${vars.treebank}/test.spacy"
    outputs:
      - "training/large/model-best/accuracy.json"

  - name: clean
    help: "Clean directories"
    script:
      - "rm -rf assets"
      - "rm -rf corpus"
      - "rm -rf packages"
      - "rm -rf metrics"
      - "rm -rf training"
      - "rm -rf vectors"
      - "rm project.lock"
       

